KEY_OVERRIDE_ENABLE = yes # needed for ctrl+bspc -> del
ENCODER_ENABLE = no
MOUSEKEY_ENABLE = no
RGBLIGHT_ENABLE = yes
NKRO_ENABLE = yes

# MUSIC_ENABLE = no
# CONSOLE_ENABLE = no
# COMMAND_ENABLE = no
# MOUSEKEY_ENABLE = no
# SPACE_CADET_ENABLE = no
# GRAVE_ESC_ENABLE = no
# MAGIC_ENABLE = no
